listenAddr = "127.0.0.1:5000"
verbose = true

[gateway]
	# AllowedHosts = ["abc.localhost:8443", "abc.localhost:8080",	"myinternaldomain.local"] 
	[gateway.matrix]
		enabled = true
[rewrite]
	[rewrite.fcm]
		enabled = false
		# key = ""
	[rewrite.gotify]
		enabled = false
		#address = "gotify1.unifiedpush.org:443"
		#scheme = "https"

# see https://github.com/UnifiedPush/common-proxies/blob/main/docs/config.md for more info
