on:
  push:
    tags:
      - 'v*'

name: Build and release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://golang:1.15
        with:
          args: make all
          # apparently github auto-mounts dirs so no volumes needed
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "bin/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


