
on: [push, pull_request]
  

name: Build test

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container: golang:1.15
    steps:
      - uses: actions/checkout@v2
      - run: make test 


